name: Container

on: push 

jobs:
  node-docker:
    runs-on: self-hosted
    container:  
      image: node:alpine
    steps:
      - name: Log node version 
        run: |
          node -v
          vat /etc/os-release
