name: "nodejs"
on: [workflow_dispatch]

jobs:
  nodejs:
    strategy:
      matrix: 
        os: [self-hosted, ubuntu-latest]
        nodejs: [10,18,16]
      fail-fast: true
    runs-on: ${{ nodejs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ nodejs.nodejs}}
      - run: npm ci
      - run: npm test
      - run: node -v

      


